name: ldfluttersmartcity2
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # flutter 网络请求框架
  dio: ^3.0.9
  #界面适配框架
  flutter_screenutil: ^1.0.2
  # 权限申请
  permission_handler: ^4.4.0+hotfix.2
  # 用户消息
  oktoast: ^2.3.2
  # json 序列化框架
  json_serializable: ^2.0.0
  # 高德地图
  decorated_flutter: ^0.12.0+1
  demo_widgets: ^0.0.3
  amap_core_fluttify: ^0.8.0
 # url_launcher: ^5.4.2
 # core_location_fluttify: ^0.1.0-dev.0
  amap_map_fluttify: ^0.22.0
  # sp键值存储
  shared_preferences: ^0.5.7+1
  # 事件总线
  event_bus: ^1.1.0
  # 状态管理
  provider: ^4.0.5+1
  # 可拖动进度条
  flutter_seekbar:
    git: https://github.com/LiuC520/flutter_seekbar.git




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - raw/
    - images/
    - images/catalog_lighting_bg.png
    - images/login_logo.png
    - images/bian.png
    - images/ebox.png
    - images/energy01.png
    - images/energy02.png
    - images/energy03.png
    - images/energy04.png
    - images/energy05.png
    - images/light_off.png
    - images/light_on.png
    - images/light_on2.png
    - images/light_warning.png
    - images/v-logo.png
    - images/test_icon.png
    - images/restoration.png
    - images/refresh.png
    - images/group.png
    - images/location.png
    - images/my_user.png
    - images/lamp_location.png
    - images/light_selected.png
    - images/wiresafe_selected.png
    - images/ebox_selected.png
    - images/wiresafe_warning.png
    - images/wiresafe.png



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
